//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostForm.HostServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myuri.org/Simple", ConfigurationName="HostServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myuri.org/Simple/IService/GetAuthor", ReplyAction="http://myuri.org/Simple/IService/GetAuthorResponse")]
        HostForm.HostServiceReference.GetAuthorResponse GetAuthor(HostForm.HostServiceReference.GetAuthorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthor", WrapperNamespace="http://myuri.org/Simple", IsWrapped=true)]
    public partial class GetAuthorRequest {
        
        public GetAuthorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorResponse", WrapperNamespace="http://myuri.org/Simple", IsWrapped=true)]
    public partial class GetAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myuri.org/Simple", Order=0)]
        public string GetAuthorResult;
        
        public GetAuthorResponse() {
        }
        
        public GetAuthorResponse(string GetAuthorResult) {
            this.GetAuthorResult = GetAuthorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : HostForm.HostServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<HostForm.HostServiceReference.IService>, HostForm.HostServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HostForm.HostServiceReference.GetAuthorResponse GetAuthor(HostForm.HostServiceReference.GetAuthorRequest request) {
            return base.Channel.GetAuthor(request);
        }
    }
}
