//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostForm.HostServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myuri.org/Simple", ConfigurationName="HostServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myuri.org/Simple/IService/GetAuthor", ReplyAction="http://myuri.org/Simple/IService/GetAuthorResponse")]
        HostForm.HostServiceReference.GetAuthorResponse GetAuthor(HostForm.HostServiceReference.GetAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://myuri.org/Simple/IService/GetAuthor", ReplyAction="http://myuri.org/Simple/IService/GetAuthorResponse")]
        System.IAsyncResult BeginGetAuthor(HostForm.HostServiceReference.GetAuthorRequest request, System.AsyncCallback callback, object asyncState);
        
        HostForm.HostServiceReference.GetAuthorResponse EndGetAuthor(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthor", WrapperNamespace="http://myuri.org/Simple", IsWrapped=true)]
    public partial class GetAuthorRequest {
        
        public GetAuthorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorResponse", WrapperNamespace="http://myuri.org/Simple", IsWrapped=true)]
    public partial class GetAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myuri.org/Simple", Order=0)]
        public string GetAuthorResult;
        
        public GetAuthorResponse() {
        }
        
        public GetAuthorResponse(string GetAuthorResult) {
            this.GetAuthorResult = GetAuthorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : HostForm.HostServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HostForm.HostServiceReference.GetAuthorResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HostForm.HostServiceReference.GetAuthorResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<HostForm.HostServiceReference.IService>, HostForm.HostServiceReference.IService {
        
        private BeginOperationDelegate onBeginGetAuthorDelegate;
        
        private EndOperationDelegate onEndGetAuthorDelegate;
        
        private System.Threading.SendOrPostCallback onGetAuthorCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAuthorCompletedEventArgs> GetAuthorCompleted;
        
        public HostForm.HostServiceReference.GetAuthorResponse GetAuthor(HostForm.HostServiceReference.GetAuthorRequest request) {
            return base.Channel.GetAuthor(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAuthor(HostForm.HostServiceReference.GetAuthorRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAuthor(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HostForm.HostServiceReference.GetAuthorResponse EndGetAuthor(System.IAsyncResult result) {
            return base.Channel.EndGetAuthor(result);
        }
        
        private System.IAsyncResult OnBeginGetAuthor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HostForm.HostServiceReference.GetAuthorRequest request = ((HostForm.HostServiceReference.GetAuthorRequest)(inValues[0]));
            return this.BeginGetAuthor(request, callback, asyncState);
        }
        
        private object[] OnEndGetAuthor(System.IAsyncResult result) {
            HostForm.HostServiceReference.GetAuthorResponse retVal = this.EndGetAuthor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAuthorCompleted(object state) {
            if ((this.GetAuthorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAuthorCompleted(this, new GetAuthorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAuthorAsync(HostForm.HostServiceReference.GetAuthorRequest request) {
            this.GetAuthorAsync(request, null);
        }
        
        public void GetAuthorAsync(HostForm.HostServiceReference.GetAuthorRequest request, object userState) {
            if ((this.onBeginGetAuthorDelegate == null)) {
                this.onBeginGetAuthorDelegate = new BeginOperationDelegate(this.OnBeginGetAuthor);
            }
            if ((this.onEndGetAuthorDelegate == null)) {
                this.onEndGetAuthorDelegate = new EndOperationDelegate(this.OnEndGetAuthor);
            }
            if ((this.onGetAuthorCompletedDelegate == null)) {
                this.onGetAuthorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthorCompleted);
            }
            base.InvokeAsync(this.onBeginGetAuthorDelegate, new object[] {
                        request}, this.onEndGetAuthorDelegate, this.onGetAuthorCompletedDelegate, userState);
        }
    }
}
